import {describe,it,expect,vi} from 'vitest';
import {aboutBeat,decisionFor,link,makeDocument,readRoute,words} from '../src/model';
import {errorMessage,request,saveJson} from '../src/api';
import {finding,scene,state} from './fixtures';
describe('navigation and evidence',()=>{
  it('round trips deep links and falls back on unknown pages',()=>{location.hash=link('scene',state.run_id,'B-17');expect(readRoute()).toEqual({page:'scene',run:state.run_id,beat:'B-17',finding:null,filter:null,record:null,q:null});location.hash='#invalid';expect(readRoute().page).toBe('overview');expect(link('overview')).toBe('#overview');});
  it('does not associate two absent identifiers and resolves every source kind',()=>{expect(aboutBeat({...finding,requirement_id:null},scene.beats[1])).toBe(false);for(const id of ['B-01','CR-01','T-1','MARA','MUG'])expect(aboutBeat({...finding,requirement_id:id},scene.beats[0])).toBe(true);expect(aboutBeat({...finding,requirement_id:'other'},scene.beats[0])).toBe(false);});
  it('recognizes withdrawn decisions and selects the most recent record',()=>{const d={decision_id:'d',finding_id:finding.finding_id,action:'accept_exception',actor:'Sue',role:'script_supervisor' as const,reason:'Intent',finding_sha256:'old',at:'date'};expect(decisionFor(finding,[]).stale).toBe(false);expect(decisionFor(finding,[d]).stale).toBe(true);expect(decisionFor(finding,[d,{...d,finding_sha256:finding.record_sha256}]).stale).toBe(false);expect(words('no_viable_coverage')).toBe('no viable coverage');});
  it('converts form fields without inventing camera report agreement',()=>{const form=new FormData();form.set('take_id',' T-2 ');form.set('lens_mm','50');form.set('report_lens_mm','85');form.set('visible_people','MARA, DELPHINE, ');form.set('usable','on');const doc=makeDocument('take',form);expect(doc).toMatchObject({take_id:'T-2',lens_mm:50,usable:true,preferred:false,visible_people:['MARA','DELPHINE'],camera_report_row:{lens_mm:85}});expect(makeDocument('rights_record',new FormData())).toMatchObject({expires_on:null});form.set('expires_on','2027-01-01');expect(makeDocument('rights_record',form)).toMatchObject({expires_on:'2027-01-01'});});
});
describe('bounded API',()=>{
  it('sends same-origin JSON and reports server errors',async()=>{const fetcher=vi.fn().mockResolvedValueOnce({ok:true,json:async()=>({yes:true})}).mockResolvedValueOnce({ok:false,status:403,json:async()=>({error:'Wrong role'})}).mockResolvedValueOnce({ok:false,status:409,json:async()=>({message:'Wait'})}).mockResolvedValueOnce({ok:false,status:502,json:async()=>({})});vi.stubGlobal('fetch',fetcher);expect(await request('state')).toEqual({yes:true});expect(fetcher.mock.calls[0][0]).toBe('/api/state');await expect(request('decide')).rejects.toThrow('Wrong role');await expect(request('wrap')).rejects.toThrow('Wait');await expect(request('scene')).rejects.toThrow('502');});
  it('keeps bad JSON and network failures recoverable',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce({json:async()=>{throw new Error('parse');}}).mockRejectedValueOnce(new Error('Offline')));await expect(request('scene')).rejects.toThrow('unreadable');await expect(request('scene')).rejects.toThrow('Offline');expect(errorMessage(new Error('reason'))).toBe('reason');expect(errorMessage(null)).toContain('unavailable');});
  it('aborts after 35 seconds without retrying a write',async()=>{vi.useFakeTimers();const fetcher=vi.fn((_url,options)=>new Promise((_resolve,reject)=>options.signal.addEventListener('abort',()=>reject(new Error('Abort')))));vi.stubGlobal('fetch',fetcher);const pending=expect(request('approve',{approve:true})).rejects.toThrow('timed out');await vi.advanceTimersByTimeAsync(35001);await pending;expect(fetcher).toHaveBeenCalledTimes(1);vi.useRealTimers();});
  it('downloads an exact portable JSON document',()=>{const create=vi.fn(()=> 'blob:receipt');const revoke=vi.fn();vi.stubGlobal('URL',Object.assign(URL,{createObjectURL:create,revokeObjectURL:revoke}));const click=vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});saveJson('receipt.json',{run_id:'one'});expect(create).toHaveBeenCalled();expect(click).toHaveBeenCalledOnce();expect(revoke).toHaveBeenCalledWith('blob:receipt');});
});
