import {useState} from 'react';
import {Actions} from './Actions';
import {History} from './History';
import {Intake} from './Intake';
import {SceneView} from './SceneView';
import {link,pages,roles} from './model';
import {useWorkspace} from './useWorkspace';
import {readPreference,writePreference,storageNotice} from './storage';
import type {Page,Role} from './types';
export function App() {
  const w=useWorkspace();
  const [role,setRole]=useState<Role>(()=>{const saved=readPreference('lasttake.role');return saved && Object.hasOwn(roles,saved)?saved as Role:'script_supervisor';});
  const [guided,setGuided]=useState(false);
  const [intake,setIntake]=useState(false);
  const {state,scene,route}=w;
  return <div className="app-shell"><a href="#main" className="skip-link" onClick={e=>{e.preventDefault();document.getElementById('main')?.focus();}}>Skip to main content</a>
    <aside className="navigation"><a className="brand" href={link('overview',state?.run_id)}><span className="brand-mark" aria-hidden="true">L<span>◢</span></span><span>LASTTAKE<small>BEFORE THE SET COMES DOWN</small></span></a>
      <p className="nav-label">Shoot day workspace</p><nav aria-label="Main navigation">{Object.entries(pages).map(([key,label],index)=><a key={key} href={link(key as Page,state?.run_id)} aria-current={route.page===key?'page':undefined}><span aria-hidden="true">{['◫','▤','✓','↗'][index]}</span>{label}</a>)}</nav>
      <div className="nav-bottom"><p className="synthetic">Synthetic demo</p><p>One fictional production.<br/>Real evidence and approval workflows.</p><button className="guide-toggle" aria-pressed={guided} onClick={()=>setGuided(!guided)}>{guided?'Close guided demo':'Open guided demo'}</button></div>
    </aside><div className="workspace"><header className="topbar"><div><span className="production-dot" aria-hidden="true"/>The Last Ferry <span className="muted">/ Scene 42</span></div><label>Demo role<select value={role} onChange={e=>{setRole(e.target.value as Role);writePreference('lasttake.role',e.target.value);}}>{Object.entries(roles).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></header>
      <main id="main" tabIndex={-1} aria-busy={w.busy}><div className="page-heading"><div><p className="eyebrow">Production assurance · fictional shoot day</p><h1>{pages[route.page]}</h1><p>{route.page==='scene'?'The script, the takes, and what still needs attention.':route.page==='actions'?'A decision belongs to a person and the exact evidence they reviewed.':route.page==='history'?'A traceable handoff, with the open items kept in view.':'Know what you have before you wrap the set.'}</p></div><div className="toolbar">{state && <button disabled={w.busy} onClick={()=>void w.refresh()}>Refresh saved state</button>}<button className="primary" disabled={w.busy} onClick={()=>{setIntake(false);void w.create();}}>New shoot-day run</button></div></div>
        {guided && <section className="guide panel"><h2>Walk through a fictional shoot day</h2><ol><li>Create a run and start the wrap checkpoint.</li><li>Review the script, then answer the pickup request as the 1st AD.</li><li>Add evidence using the labelled synthetic examples.</li><li>Review changed findings as the script supervisor and DIT.</li><li>Request a new wrap approval, answer as the 1st AD, then publish the turnover.</li></ol><p>This demo uses a scripted planner and an offline lexical interpreter with real Strands interrupts. No Bedrock inference or external message is sent by these demo flows.</p></section>}
        {storageNotice() && <p className="warning" role="status">{storageNotice()}</p>}
        {w.busy && <div className="loading" role="status"><span className="spinner" aria-hidden="true"/>Reading or saving the shoot day…</div>}
        {w.error && <div className="error" role="alert"><h2>We couldn't complete that request</h2><p>{w.error}</p><p>Refresh saved state before retrying a write. Your form entries are kept.</p><button disabled={w.busy} onClick={()=>void w.refresh()}>Retry loading saved state</button>{!state && <button disabled={w.busy} onClick={()=>void w.recover()}>Start a separate session</button>}</div>}
        {w.message && <p className="saved" role="status">{w.message}</p>}
        {!state && !w.busy && !w.error && <section className="welcome panel"><p className="eyebrow">Ready when you are</p><h2>Bring the shoot day into focus.</h2><p>Create a saved run of The Last Ferry's fictional scene. Review the script and supplied records, reconcile the exceptions, and prepare a handoff that says what is still open.</p><div className="welcome-grid"><div><span>01</span><h3>Read the scene</h3><p>Script beats and take reports together.</p></div><div><span>02</span><h3>Review the gaps</h3><p>Evidence, ownership and a next action.</p></div><div><span>03</span><h3>Hand off the record</h3><p>Versioned receipts and human decisions.</p></div></div><button className="primary" onClick={()=>void w.create()}>Start this fictional shoot day</button></section>}
        {state && scene && <>
          {route.page==='overview' && <><section className="summary panel"><div><p className="eyebrow">Current saved run</p><h2>The Last Ferry</h2><p>{scene.scene_heading}</p><span className="badge">{state.wrap_approved?'Wrap decision recorded':state.counts?'Checkpoint saved':'Awaiting checkpoint'}</span><p className="fine">{scene.revision} · {scene.take_count} supplied takes</p></div><div className="summary-action"><p>{state.headline ?? 'These records have not been assessed yet. Run the checkpoint to see what the evidence supports.'}</p><a className="button primary" href={link('scene',state.run_id)}>Open scene workspace</a></div></section>
            {state.counts && <div className="stats"><div><span>{state.counts.covered_with_evidence}<small> / {state.counts.required_beats}</small></span><p>Beats covered with evidence</p></div><div><span>{state.counts.raising_exceptions}</span><p>Beats raising exceptions</p></div><div><span>{state.counts.without_release_record}</span><p>Beats missing release records</p></div></div>}
            <section className="panel"><h2>What needs attention</h2>{state.counts ? <><p>{state.causes.length} cause(s) currently prevent eligibility. Human-accepted exceptions stay visible in the record.</p><ul className="action-list">{state.causes.map((cause,i)=><li key={`${cause.requirement_id}-${i}`}><strong>{roles[cause.required_role]}</strong><span>{scene.locations[cause.requirement_id] ?? cause.requirement_id}</span><small>{cause.reason}</small></li>)}</ul><a className="button" href={link('actions',state.run_id)}>Review my actions</a></> : <button className="primary" disabled={w.busy} onClick={()=>void w.act('checkpoint')}>Run wrap checkpoint</button>}</section>
          </>}
          {route.page==='scene' && <><div className="toolbar scene-actions"><span className="fine">{state.counts?state.headline:'Not assessed yet. Absent evidence is never a pass.'}</span>{!state.counts && <button className="primary" disabled={w.busy} onClick={()=>void w.act('checkpoint')}>Run wrap checkpoint</button>}<button disabled={w.busy} onClick={()=>setIntake(!intake)} aria-expanded={intake}>Add take or release</button></div>{intake && <Intake scene={scene} busy={w.busy} guided={guided} onClose={()=>setIntake(false)} onSubmit={(kind,document)=>w.act('ingest',{kind,document})}/>}<SceneView scene={scene} state={state} selected={route.beat}/></>}
          {route.page==='actions' && <Actions scene={scene} state={state} role={role} busy={w.busy} act={w.act}/>}
          {route.page==='history' && w.session && <History key={state.run_id} state={state} session={w.session} events={w.events} role={role} busy={w.busy} act={w.act} handle={w.handle}/>}
          <footer><details><summary>Run details & execution labels</summary><dl className="metadata"><dt>Saved run</dt><dd>{state.run_id}</dd><dt>Framework</dt><dd>Strands Agents SDK</dd><dt>Planner</dt><dd>offline-scripted/1.0.0</dd><dt>Interpreter reported by API</dt><dd>{state.interpreter}</dd><dt>State store reported by API</dt><dd>{state.run_state_store}</dd><dt>Policy</dt><dd>{scene.policy_version}</dd></dl><p>Demo role selection is not staff authentication. The browser holds a session handle and preferences; records and decisions are stored by the backend.</p></details><p>Synthetic records only. This workflow reconciles supplied evidence; it does not determine creative quality or legal sufficiency.</p></footer>
        </>}
      </main></div></div>;
}
